### ISSUE TITLE
Why is the path still referring to mavlink 1.0 ? +one more thing

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/mavlink#269]
So I see:
https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/ardupilotmega.xml

1.0  ? - why is there no /2.0/ - is it a purely cosmetic thing?

nor can I see message 244 (MESSAGE_INTERVAL)   - nor is it in common

my program (on a microcontroller) is fine with this line:
```
 mavlink_msg_param_request_read_send(MAVLINK_COMM_0, apm_mav_system, apm_mav_component, "BATT2_CRT_VOLT",-1);
```
 
but this one fails to set VFR_HUD rate on telemetry.
```
mavlink_msg_message_interval_send(MAVLINK_COMM_0, MAVLINK_MSG_ID_VFR_HUD, 500000);
```
no error - just that it does not work (it sends a 244 packet.)

**Comment by tridge** [comment]
the XML for mavlink 1.0 and 2.0 is the same, thus the revision wasn't changed, this was a deliberate decision to make change to 2.0 easier

**Comment by tridge** [comment]
for the interval issue, you'd need to provide tlogs and info on flight controller, or debug in SITL. Not enough info, sorry.

**Comment by AndKe** [comment]
@tridge thank you for clearing that up.
As for intervals, It's so long ago now, and I use individual intervals (MAV_CMD_SET_MESSAGE_INTERVAL) now. (which works great)
