### ISSUE TITLE
Does the mavlink fork from Ardupilot work with MAVSDK?

### ISSUE THREAD

**Issue by qishen** [ArduPilot/mavlink#333]
I'm trying to use `MAVSDK` to communicate with ArduCopter and it seems `MAVSDK` is mainly targeted for PX4 but I wonder if it will work if I swap the default `mavlink` library with the `mavlink` fork from here. I'm also curious what's the main reason to maintain a fork of `mavlink` here.

**Comment by rmackay9** [comment]
Hi @qishen,

AP maintains it's own mavlink fork just to protect us from incompatible upstream changes.  We do this for pretty much all external projects so it's not that we don't trust the mavlink maintainers of course, we work with them closely, it's just about maintaining stability.

AP can work with MAVSDK and there are a couple of developers who have put work into this.  My understanding is that  there is still a bit more work to do to make AP completely compatible but it should work.  I think even if AP's mavlink fork wasn't used it would still work.

This is really a question so I will close this issue.  Txs.
